site_name: ray-tracing-practice
site_url: https://the-last-stand.github.io/ray-tracing-practice/
repo_name: ray-tracing-practice
repo_url: https://github.com/the-last-stand/ray-tracing-practice
site_description: ""
site_author: None
copyright: 'Copyright &copy; 2023 None'
remote_branch: gh-pages
edit_uri: edit/main/docs/

theme:
  language: en
  name: 'material'
  palette:
    - scheme: default
      primary: 'deep orange'
      accent: 'pink'
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.top
#    - navigation.tabs

#extra_css:
#  - 'css/app.css'   

markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css


plugins:
  - search
  - git-revision-date
#  - macros

extra:
  versions:
    ray_tracing: '4.0.0-alpha.1'

nav:
  - 'Home':
      - 'Overview': index.md

      - 'In one weekend': 
        - 'Overview': one_weekend/in_one_weekend.md
        - 'Output an image': one_weekend/output_an_image.md
        - 'The vec3 Class': one_weekend/the_vec3_class.md
        - 'Rays, a Simple Camera, and Background': one_weekend/rays_a_simple_camera_and_background.md
        # - 'Adding a Sphere':
        # - 'Surface Normals and Multiple Objects':
        # - 'Moving Camera Code Into Its Own Class':
        # - 'Antialiasing':
        # - 'Diffuse Materials':
        # - 'Metal':
        # - 'Dielectrics':
        # - 'Positionable Camera':
        # - 'Defocus Blur':
        # - 'Where Next?':
        # - 'Acknowledgments':