site_name: ray-tracing-practice
site_url: https://the-last-stand.github.io/ray-tracing-practice/
repo_name: LEA
repo_url: https://github.com/the-last-stand/ray-tracing-practice
site_description: ""
site_author: None
copyright: 'Copyright &copy; 2023 None'
remote_branch: gh-pages
edit_uri: edit/main/docs/

theme:
  language: en
  name: 'material'
  palette:
    - scheme: default
      primary: 'deep orange'
      accent: 'pink'
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
#    - navigation.tabs

#extra_css:
#  - 'css/app.css'

markdown_extensions:
  - codehilite:
      guess_lang: false

plugins:
  - search
  - git-revision-date
#  - macros

# extra:
#   versions:

nav:
  - 'Home':
      - 'Overview': index.md
      - 'In one weekend': in_one_weekend.md